export const REMOVE_ARTICLE = 'REMOVE ARTICLE';
export const REMOVE_COMMENT = 'REMOVE COMMENT';
export const START_LOAD_ARTICLES = 'START LOAD ARTICLES';
export const LOADING_ARTICLES_SUCCESS = 'LOADING ARTICLES SUCCESS';
export const LOADING_ARTICLES_ERROR = 'LOADING ARTICLES ERROR';
export const ADD_ARTICLE = 'ADD ARTICLE';
