export const START_LOAD_ARTICLES = 'START LOAD ARTICLES';
export const LOADING_ARTICLES_SUCCESS = 'LOADING ARTICLES SUCCESS';
export const LOADING_ARTICLES_ERROR = 'LOADING ARTICLES ERROR';

export const START_ADD_ARTICLE = 'START ADD ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD ARTICLE SUCCESS';
export const ADD_ARTICLE_ERROR = 'ADD ARTICLE ERROR';

export const START_REMOVE_ARTICLE = 'START REMOVE ARTICLE';
export const REMOVE_ARTICLE_SUCCESS = 'REMOVE ARTICLE SUCCESS';
export const REMOVE_ARTICLE_ERROR = 'REMOVE ARTICLE ERROR';

export const START_REMOVE_COMMENT = 'START REMOVE COMMENT';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE COMMENT SUCCESS';
export const REMOVE_COMMENT_ERROR = 'REMOVE COMMENT ERROR';

export const START_ADD_COMMENT = 'START ADD COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD COMMENT SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD COMMENT ERROR';
